# Generated by Django 2.2 on 2019-04-21 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190421_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
